import { beforeAll, beforeEach, afterAll, describe, expect, it, vi } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { criarManifestoCadastroMestre, criarRevisaoCadastroMestre, decidirOperacoesCadastroMestre } from '../core/cadastro-mestre-approval-engine.js';
import { criarPlanoReconstrucaoCadastroMestre } from '../core/cadastro-mestre-reconstruction-engine.js';
import { prepararAprovacaoArquivoCadastroMestre } from '../src/services/cadastro-mestre-preview.js';
import { executarReconstrucaoCadastroMestre, hashReconstrucao } from '../scripts/lib/cadastro-mestre-reconstruction.mjs';
import { arquivoCadastro, contexto, SheetJS } from './fixtures/cadastro-mestre-arquivo.js';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { main, salvarSnapshotDuravel } from '../scripts/reconstruir-cadastro-mestre.mjs';

const aprovar = m => decidirOperacoesCadastroMestre(m, criarRevisaoCadastroMestre(m), m.operacoes.filter(o => o.aprovavel).map(o => o.id), 'APROVADO');
describe('Contrato do universo — preparação pura', () => {
  it('ausente/filtrado vira remoção revisável e vazio de pertencente preserva campo', async () => {
    const { manifesto } = await prepararAprovacaoArquivoCadastroMestre(arquivoCadastro(), contexto, SheetJS);
    const plano = criarPlanoReconstrucaoCadastroMestre(manifesto, aprovar(manifesto));
    expect(plano.resumo).toEqual({ antes: 8, depois: 4, inseridos: 1, atualizados: 1, removidos: 5 });
    expect(plano.universo).toEqual(['001', '002', '008', '1000']);
    expect(plano.esperados.find(p => p.codigo_produto === '002').calculado).toEqual(contexto.produtos[1]);
    expect(manifesto.operacoes.filter(o => o.acao === 'DELETE').every(o => o.tabela === 'dicionario_master_produtos')).toBe(true);
    expect(() => criarPlanoReconstrucaoCadastroMestre(manifesto, criarRevisaoCadastroMestre(manifesto))).toThrow('Todas');
    const r = decidirOperacoesCadastroMestre(manifesto, aprovar(manifesto), [manifesto.operacoes.find(o => o.acao === 'DELETE').id], 'REJEITADO');
    expect(() => criarPlanoReconstrucaoCadastroMestre(manifesto, r)).toThrow('Todas');
  });
  it.each([{ rows: [] }, { rows: [{ codigo_produto: '001', tipo: 'P', descr_origem: 'Produzido', descricao: 'A' }, { codigo_produto: '001', tipo: 'P', descr_origem: 'Produzido', descricao: 'B' }] }])('universo vazio/erro de identidade bloqueia remoções e execução', ({ rows }) => {
    const m = criarManifestoCadastroMestre(rows, contexto, { modo: 'RECONSTRUCAO_UNIVERSO' });
    expect(m.reconstrucao_bloqueada).toBe(true);
    expect(m.operacoes.every(o => !o.aprovavel)).toBe(true);
    expect(() => criarPlanoReconstrucaoCadastroMestre(m, criarRevisaoCadastroMestre(m))).toThrow('bloqueada');
  });
  it('exemplo informado pelo usuário: 6.230 → 860, 853 existentes + 7 novos, 4.853 remoções', () => {
    // Contagens reais informadas pelo usuário; registros desta prova são sintéticos.
    const produtos = Array.from({ length: 5706 }, (_, i) => ({ codigo_produto: String(i + 1), descricao: 'Atual', origem_cod: '01', familia_cod: 'F1', agrupamento_erp_valor: 'P005' }));
    const rows = [
      ...produtos.map((p, i) => ({ ...p, tipo: i < 853 ? 'P' : 'D', descr_origem: 'Produzido' })),
      ...Array.from({ length: 7 }, (_, i) => ({ codigo_produto: String(6000 + i), descricao: 'Novo', origem_cod: '01', familia_cod: 'F1', tipo: 'C', descr_origem: 'Revenda' })),
      ...Array.from({ length: 517 }, (_, i) => ({ codigo_produto: String(7000 + i), descricao: 'Excluído', tipo: 'D', descr_origem: 'Produzido' }))
    ];
    const m = criarManifestoCadastroMestre(rows, { ...contexto, produtos }, { modo: 'RECONSTRUCAO_UNIVERSO' });
    expect(m.resumo).toMatchObject({ linhas_lidas: 6230, produtos_com_preview: 860, produtos_existentes: 853, novos_produtos: 7,
      produtos_a_remover: 4853, produtos_master_antes: 5706, produtos_master_depois: 860 });
    expect(criarPlanoReconstrucaoCadastroMestre(m, aprovar(m)).resumo).toMatchObject({ depois: 860, removidos: 4853, inseridos: 7 });
  });
});

describe('Executor — PostgreSQL real em memória, sem Supabase', () => {
  let db;
  let client;
  let evidencia;
  let snapshot;
  let before;
  const protegidas = ['apontamentos_op', 'categorias_agrupamento', 'dicionario_produtos', 'historico_custos', 'mapa_produtos'];
  beforeAll(async () => { db = await PGlite.create(); }, 20000);
  afterAll(async () => { await db.close(); });
  beforeEach(async () => {
    await db.exec(`DROP SCHEMA public CASCADE; CREATE SCHEMA public;
      CREATE TABLE log_importacao_cadastro_mestre (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        arquivo_nome text NOT NULL, tipo_arquivo text NOT NULL, arquivo_hash text, identificador_lote text,
        fonte_sistema text DEFAULT 'ERP',status text DEFAULT 'processando',total_registros int DEFAULT 0,
        registros_processados int DEFAULT 0,registros_inseridos int DEFAULT 0,registros_atualizados int DEFAULT 0,
        registros_erro int DEFAULT 0,erros jsonb DEFAULT '[]',metadados_origem jsonb DEFAULT '{}',
        criado_em timestamptz DEFAULT now(),iniciado_em timestamptz DEFAULT now(),finalizado_em timestamptz);
      CREATE TABLE dicionario_master_produtos (codigo_produto text PRIMARY KEY,descricao text,origem_cod text,familia_cod text,
        agrupamento_erp_valor text,ultima_importacao_cadastro_mestre_id bigint REFERENCES log_importacao_cadastro_mestre(id),
        agrupamento_erp_importacao_id bigint REFERENCES log_importacao_cadastro_mestre(id),
        criado_em timestamptz DEFAULT now(),atualizado_em timestamptz DEFAULT now());
      CREATE TABLE categorias_origem (id text PRIMARY KEY,codigo text,descricao text);
      CREATE TABLE categorias_familia (id text PRIMARY KEY,codigo text,descricao text);
      ${protegidas.map(t => `CREATE TABLE ${t} (codigo text PRIMARY KEY,conteudo jsonb); INSERT INTO ${t} VALUES ('003','{"fato":"intacto"}');`).join('\n')}`);
    for (const table of ['categorias_origem', 'categorias_familia']) {
      const rows = table === 'categorias_origem' ? contexto.origens : contexto.familias;
      await db.query(`INSERT INTO ${table} SELECT * FROM jsonb_to_recordset($1::jsonb) AS x(id text,codigo text,descricao text)`, [JSON.stringify(rows)]);
    }
    for (const p of contexto.produtos) await db.query(`INSERT INTO dicionario_master_produtos
      (codigo_produto,descricao,origem_cod,familia_cod,agrupamento_erp_valor) VALUES ($1,$2,$3,$4,$5)`, [p.codigo_produto, p.descricao, p.origem_cod, p.familia_cod, p.agrupamento_erp_valor]);
    client = { query: vi.fn((sql, params) => db.query(sql, params)) };
    before = await ctx();
    const result = await prepararAprovacaoArquivoCadastroMestre(arquivoCadastro(), before, SheetJS);
    evidencia = { manifesto: result.manifesto, revisao: aprovar(result.manifesto) };
    snapshot = vi.fn(async () => {});
  });
  async function ctx() {
    const table = async (name, fields, key) => (await db.query(`SELECT to_jsonb(t) AS registro FROM (SELECT ${fields} FROM ${name} ORDER BY ${key}) t`)).rows.map(r => r.registro);
    return { produtos: await table('dicionario_master_produtos', '*', 'codigo_produto'),
      origens: await table('categorias_origem', 'id,codigo,descricao', 'id'), familias: await table('categorias_familia', 'id,codigo,descricao', 'id') };
  }
  const executar = (overrides = {}) => executarReconstrucaoCadastroMestre({ client, arquivo: arquivoCadastro(), evidencia, leitor: SheetJS,
    identificadorLote: 'TESTE_LOCAL', autor: 'Teste sintético', confirmacao: `RECONSTRUIR_MASTER:${hashReconstrucao(evidencia.manifesto)}`,
    salvarSnapshot: snapshot, ...overrides });

  it('insere novo, atualiza existente, remove filtrados/ausente e registra snapshot/lote', async () => {
    const result = await executar();
    expect(result).toMatchObject({ status: 'concluido', antes: 8, depois: 4, inseridos: 1, atualizados: 1, removidos: 5 });
    const after = await ctx();
    expect(after.produtos.map(p => p.codigo_produto)).toEqual(['001', '002', '008', '1000']);
    expect(after.produtos[1]).toEqual(before.produtos.find(p => p.codigo_produto === '002'));
    const lote = (await db.query('SELECT * FROM log_importacao_cadastro_mestre')).rows[0];
    expect(lote.status).toBe('concluido');
    expect(lote.metadados_origem.snapshot_master).toEqual(before.produtos);
    expect(lote.metadados_origem.registros_removidos).toBe(5);
    expect(lote.metadados_origem.snapshot_sha256).toBe(hashReconstrucao(before.produtos));
    expect(snapshot.mock.calls[0][0].snapshot_master).toEqual(before.produtos);
    for (const t of protegidas) expect((await db.query(`SELECT * FROM ${t}`)).rows).toEqual([{ codigo: '003', conteudo: { fato: 'intacto' } }]);
  });

  it('origem/família ERP preenchidas atualizam os códigos brutos do Master', async () => {
    await db.query("UPDATE dicionario_master_produtos SET origem_cod='99',familia_cod='F9' WHERE codigo_produto='001'");
    before = await ctx();
    const { manifesto } = await prepararAprovacaoArquivoCadastroMestre(arquivoCadastro(), before, SheetJS);
    evidencia = { manifesto, revisao: aprovar(manifesto) };
    const result = await executar();
    expect(result.atualizados).toBe(1);
    expect((await ctx()).produtos.find(p => p.codigo_produto === '001')).toMatchObject({ origem_cod: '01', familia_cod: 'F1', agrupamento_erp_valor: 'P801' });
    for (const t of protegidas) expect((await db.query(`SELECT * FROM ${t}`)).rows).toEqual([{ codigo: '003', conteudo: { fato: 'intacto' } }]);
  });

  it('ERP vazio preserva origem/família mesmo quando descrição e agrupamento do produto são atualizados', async () => {
    const workbook = SheetJS.read(await arquivoCadastro().arrayBuffer(), { type: 'array', cellNF: true });
    workbook.Sheets.Cadastro.E4 = { t: 's', v: '' };
    workbook.Sheets.Cadastro.F4 = { t: 's', v: '' };
    const bytes = SheetJS.write(workbook, { type: 'array', bookType: 'xls' });
    const arquivo = { name: 'cadastro.xls', arrayBuffer: async () => bytes };
    const { manifesto } = await prepararAprovacaoArquivoCadastroMestre(arquivo, before, SheetJS);
    evidencia = { manifesto, revisao: aprovar(manifesto) };
    const result = await executar({ arquivo });
    const atual = (await ctx()).produtos.find(p => p.codigo_produto === '001');
    expect(result.atualizados).toBe(1);
    expect(atual).toMatchObject({ descricao: 'Descrição atualizada çã', origem_cod: '01', familia_cod: 'F1', agrupamento_erp_valor: 'P801' });
    expect(atual.criado_em).toBe(before.produtos.find(p => p.codigo_produto === '001').criado_em);
  });

  it.each(['INSERT INTO public.dicionario_master_produtos', 'UPDATE public.dicionario_master_produtos', 'DELETE FROM public.dicionario_master_produtos', "UPDATE public.log_importacao_cadastro_mestre SET status='concluido'"])(
    'erro em %s reverte o Master inteiro e preserva snapshot/log falhou', async alvo => {
      const original = client.query;
      let injetado = false;
      client.query = vi.fn(async (sql, params) => {
        if (!injetado && sql.startsWith(alvo)) { injetado = true; return db.query('SELECT 1/0'); }
        return original(sql, params);
      });
      await expect(executar()).rejects.toThrow('revertida integralmente');
      expect((await ctx()).produtos).toEqual(before.produtos);
      const log = (await db.query('SELECT * FROM log_importacao_cadastro_mestre')).rows[0];
      expect(log).toMatchObject({ status: 'falhou', registros_inseridos: 0, registros_atualizados: 0, registros_processados: 0 });
      expect(log.metadados_origem.snapshot_master).toEqual(before.produtos);
      expect(log.metadados_origem.registros_removidos).toBe(0);
      expect(log.erros[0].code).toBe('22012');
      for (const t of protegidas) expect((await db.query(`SELECT count(*)::int AS n FROM ${t}`)).rows[0].n).toBe(1);
    });

  it('mudança do Master após aprovação bloqueia antes de log/DML', async () => {
    await db.query("UPDATE dicionario_master_produtos SET descricao='Alteração externa' WHERE codigo_produto='002'");
    await expect(executar()).rejects.toThrow('contexto mudou');
    expect(snapshot).not.toHaveBeenCalled();
    expect((await db.query('SELECT * FROM log_importacao_cadastro_mestre')).rows).toEqual([]);
    expect((await ctx()).produtos).toHaveLength(8);
  });

  it('arquivo diferente da revisão é recusado antes de qualquer escrita', async () => {
    await expect(executar({ arquivo: arquivoCadastro('xlsx') })).rejects.toThrow('Arquivo ou contexto mudou');
    expect(snapshot).not.toHaveBeenCalled();
    expect((await ctx()).produtos).toEqual(before.produtos);
    expect((await db.query('SELECT * FROM log_importacao_cadastro_mestre')).rows).toEqual([]);
  });

  it('resultado incerto de COMMIT exige consulta ao lote e não repete a carga', async () => {
    const original = client.query;
    client.query = vi.fn(async (sql, params) => {
      const result = await original(sql, params);
      if (sql === 'COMMIT') throw new Error('Conexão encerrada após enviar COMMIT');
      return result;
    });
    await expect(executar()).rejects.toThrow('COMMIT não confirmado');
    expect((await db.query('SELECT status FROM log_importacao_cadastro_mestre')).rows).toEqual([{ status: 'concluido' }]);
    expect((await ctx()).produtos).toHaveLength(4);
    expect(snapshot).toHaveBeenCalledOnce();
    expect(client.query.mock.calls.filter(([sql]) => sql === 'COMMIT')).toHaveLength(1);
  });

  it('falha no snapshot durável impede qualquer remoção', async () => {
    await expect(executar({ salvarSnapshot: async () => { throw new Error('Disco indisponível'); } })).rejects.toThrow('Disco');
    expect((await ctx()).produtos).toEqual(before.produtos);
    expect((await db.query('SELECT * FROM log_importacao_cadastro_mestre')).rows).toEqual([]);
    expect(client.query.mock.calls.some(([sql]) => sql.startsWith('DELETE FROM'))).toBe(false);
  });

  it('dependência com CASCADE é bloqueada antes de tocar fatos', async () => {
    await db.exec('CREATE TABLE dependencia (codigo text REFERENCES dicionario_master_produtos(codigo_produto) ON DELETE CASCADE)');
    await expect(executar()).rejects.toThrow('Dependências');
    expect((await ctx()).produtos).toEqual(before.produtos);
  });

  it('conexão limitada por RLS falha em vez de reconstruir um universo parcialmente visível', async () => {
    await db.exec(`CREATE ROLE cad_rebuild_limitado;
      GRANT USAGE ON SCHEMA public TO cad_rebuild_limitado;
      GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cad_rebuild_limitado;
      GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO cad_rebuild_limitado;
      ALTER TABLE dicionario_master_produtos ENABLE ROW LEVEL SECURITY;
      SET ROLE cad_rebuild_limitado;`);
    try {
      await expect(executar()).rejects.toThrow('row-level security');
      expect(snapshot).not.toHaveBeenCalled();
    } finally { await db.exec('RESET ROLE; DROP OWNED BY cad_rebuild_limitado; DROP ROLE cad_rebuild_limitado;'); }
    expect((await ctx()).produtos).toEqual(before.produtos);
    expect((await db.query('SELECT * FROM log_importacao_cadastro_mestre')).rows).toEqual([]);
  });

  it('aprovação parcial/confirmacão ausente não inicia transação', async () => {
    await expect(executar({ confirmacao: '' })).rejects.toThrow('Confirmação');
    expect(client.query).not.toHaveBeenCalled();
    const r = criarRevisaoCadastroMestre(evidencia.manifesto);
    await expect(executar({ evidencia: { ...evidencia, revisao: r } })).rejects.toThrow('Todas');
    expect(client.query).not.toHaveBeenCalled();
  });

  it('lote repetido é bloqueado e exige nova revisão', async () => {
    await executar();
    await expect(executar()).rejects.toThrow('já registrado');
    expect((await db.query('SELECT * FROM log_importacao_cadastro_mestre')).rows).toHaveLength(1);
    expect((await ctx()).produtos).toHaveLength(4);
  });
});

describe('Comando administrativo e snapshot independente', () => {
  it('snapshot é persistido integralmente e recusa sobrescrever uma evidência anterior', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'kustos-rebuild-'));
    const file = join(dir, 'snapshot.json');
    try {
      const value = { snapshot_master: contexto.produtos, lote_id: '1', snapshot_sha256: hashReconstrucao(contexto.produtos) };
      await salvarSnapshotDuravel(file, value);
      expect(JSON.parse(await readFile(file, 'utf8'))).toEqual(value);
      await expect(salvarSnapshotDuravel(file, {})).rejects.toMatchObject({ code: 'EEXIST' });
      expect(JSON.parse(await readFile(file, 'utf8'))).toEqual(value);
    } finally { await rm(dir, { recursive: true, force: true }); }
  });

  it('sem --executar valida revisão local sem depender de conexão PostgreSQL', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'kustos-rebuild-'));
    const file = join(dir, 'revisao.json');
    const consoleSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    vi.stubEnv('CADASTRO_MESTRE_DATABASE_URL', 'postgresql://inacessivel.invalid/banco');
    try {
      const { manifesto } = await prepararAprovacaoArquivoCadastroMestre(arquivoCadastro(), contexto, SheetJS);
      await salvarSnapshotDuravel(file, { manifesto, revisao: aprovar(manifesto) });
      await main(['--revisao', file]);
      expect(JSON.parse(consoleSpy.mock.calls[0][0])).toMatchObject({ somente_validacao_local: true, antes: 8, depois: 4, removidos: 5 });
      await expect(main(['--revisao', file, '--executar'])).rejects.toThrow('Execução exige');
    } finally { consoleSpy.mockRestore(); vi.unstubAllEnvs(); await rm(dir, { recursive: true, force: true }); }
  });
});
