-- FASE 2A — Estrutura auditável do Cadastro Mestre.
-- Escopo deliberadamente aditivo: não altera dados ERP existentes nem runtime.

begin;

create table public.log_importacao_cadastro_mestre (
  id bigint generated by default as identity primary key,
  arquivo_nome text not null,
  tipo_arquivo text not null,
  arquivo_hash text,
  identificador_lote text,
  fonte_sistema text not null default 'ERP',
  iniciado_em timestamptz not null default now(),
  finalizado_em timestamptz,
  status text not null default 'processando',
  total_registros integer not null default 0,
  registros_processados integer not null default 0,
  registros_inseridos integer not null default 0,
  registros_atualizados integer not null default 0,
  registros_erro integer not null default 0,
  erros jsonb not null default '[]'::jsonb,
  metadados_origem jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),

  constraint log_importacao_cadastro_mestre_tipo_arquivo_check
    check (tipo_arquivo in ('XLSM', 'XLSX', 'XLS')),

  constraint log_importacao_cadastro_mestre_status_check
    check (
      status in (
        'processando',
        'concluido',
        'concluido_com_erros',
        'falhou',
        'cancelado'
      )
    ),

  constraint log_importacao_cadastro_mestre_identificacao_check
    check (
      arquivo_hash is not null
      or identificador_lote is not null
    ),

  constraint log_importacao_cadastro_mestre_contagens_check
    check (
      total_registros >= 0
      and registros_processados >= 0
      and registros_inseridos >= 0
      and registros_atualizados >= 0
      and registros_erro >= 0
    )
);

alter table public.log_importacao_cadastro_mestre
  enable row level security;

create index idx_log_importacao_cadastro_mestre_hash
  on public.log_importacao_cadastro_mestre (arquivo_hash)
  where arquivo_hash is not null;

create index idx_log_importacao_cadastro_mestre_lote
  on public.log_importacao_cadastro_mestre (identificador_lote)
  where identificador_lote is not null;

alter table public.dicionario_master_produtos
  add column ultima_importacao_cadastro_mestre_id bigint;

alter table public.dicionario_master_produtos
  add constraint dicionario_master_produtos_ultima_importacao_fkey
  foreign key (ultima_importacao_cadastro_mestre_id)
  references public.log_importacao_cadastro_mestre (id)
  on delete restrict;

create index idx_dicionario_master_produtos_ultima_importacao
  on public.dicionario_master_produtos (ultima_importacao_cadastro_mestre_id)
  where ultima_importacao_cadastro_mestre_id is not null;

commit;
