export function getDomRefs() {
  return {
    userBox:       document.getElementById('userBox'),
    userLabel:     document.getElementById('userLabel'),
    logoutBtn:     document.getElementById('logoutBtn'),
    loginOverlay:  document.getElementById('loginOverlay'),
    loginForm:     document.getElementById('loginForm'),
    loginUsername: document.getElementById('loginUsername'),
    loginPassword: document.getElementById('loginPassword'),
    loginError:    document.getElementById('loginError'),
    loginBtn:      document.getElementById('loginBtn'),
    navItems: Array.from(document.querySelectorAll('[data-view-trigger]')),
    views: { import: document.getElementById('view-import'), report: document.getElementById('view-report'), op: document.getElementById('view-op'), documentation: document.getElementById('view-documentation') },
    dropZone: document.getElementById('dropZone'), fileInput: document.getElementById('fileInput'), importDate: document.getElementById('importDate'),
    dropZoneOp: document.getElementById('dropZoneOp'), importOpInput: document.getElementById('importOpInput'),
    selOpEstagio: document.getElementById('sel-op-estagio'), selOpOrigem: document.getElementById('sel-op-origem'), selOpOp: document.getElementById('sel-op-op'), selOpProduto: document.getElementById('sel-op-produto'),
    dtOpStart: document.getElementById('dt-op-start'), dtOpEnd: document.getElementById('dt-op-end'),
    analisarOpBtn: document.getElementById('analisar-op-btn'), opTableBody: document.getElementById('op-table-body'),
    opDrillPanel: document.getElementById('op-drill-panel'), opDrillTitle: document.getElementById('op-drill-title'), opDrillBody: document.getElementById('op-drill-body'),
    orphansBanner: document.getElementById('orphansBanner'), orphansCount: document.getElementById('orphansCount'), orphansMessage: document.getElementById('orphansMessage'),
    searchProduct: document.getElementById('searchProduct'), productSuggestions: document.getElementById('productSuggestions'),
    dtStart: document.getElementById('dtStart'), dtEnd: document.getElementById('dtEnd'), selO: document.getElementById('selO'), selF: document.getElementById('selF'), selA: document.getElementById('selA'), selI: document.getElementById('selI'),
    analyzeBtn: document.getElementById('analyzeBtn'), exportBtn: document.getElementById('exportBtn'), activeFilterChips: document.getElementById('activeFilterChips'),
    reportContent: document.getElementById('reportContent'), tablePanel: document.getElementById('tablePanel'), tableBody: document.getElementById('tableBody'),
    kpiItens: document.getElementById('kpiItens'), kpiAlertas: document.getElementById('kpiAlertas'), kpiRegime: document.getElementById('kpiRegime'), kpiMedia: document.getElementById('kpiMedia'),
    kpiCards: Array.from(document.querySelectorAll('[data-kpi-filter]')),
    drillPanel: document.getElementById('drillPanel'), drillTitle: document.getElementById('drillTitle'), drillSubtitle: document.getElementById('drillSubtitle'), drillBody: document.getElementById('drillBody'), drillClose: document.getElementById('drillClose'),
    mainChartPanel: document.getElementById('mainChartPanel'), mainChart: document.getElementById('mainChart'),
    topVariationsPanel: document.getElementById('topVariationsPanel'), topIncreasesList: document.getElementById('topIncreasesList'), topReductionsList: document.getElementById('topReductionsList'),
    trendChartPanel: document.getElementById('trendChartPanel'), trendChart: document.getElementById('trendChart'), trendTitle: document.getElementById('trendTitle'), trendBadge: document.getElementById('trendBadge'), trendFallback: document.getElementById('trendFallback'),
    docSelector: document.getElementById('docSelector'), docEditBtn: document.getElementById('docEditBtn'), docSaveBtn: document.getElementById('docSaveBtn'), docCancelBtn: document.getElementById('docCancelBtn'),
    docViewPanel: document.getElementById('docViewPanel'), docContent: document.getElementById('docContent'), docEditPanel: document.getElementById('docEditPanel'), docEditor: document.getElementById('docEditor'), docPreview: document.getElementById('docPreview')
  };
}
